//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.16 at 06:07:16 PM BRT 
//


package com.soap.api;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.soap.api package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.soap.api
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetCustomDetailResponse }
     * 
     */
    public GetCustomDetailResponse createGetCustomDetailResponse() {
        return new GetCustomDetailResponse();
    }

    /**
     * Create an instance of {@link IdProdutoResponse }
     * 
     */
    public IdProdutoResponse createIdProdutoResponse() {
        return new IdProdutoResponse();
    }

    /**
     * Create an instance of {@link CustomDetail }
     * 
     */
    public CustomDetail createCustomDetail() {
        return new CustomDetail();
    }

    /**
     * Create an instance of {@link GetAllCustomRespone }
     * 
     */
    public GetAllCustomRespone createGetAllCustomRespone() {
        return new GetAllCustomRespone();
    }

    /**
     * Create an instance of {@link GetCustomDetailRequest }
     * 
     */
    public GetCustomDetailRequest createGetCustomDetailRequest() {
        return new GetCustomDetailRequest();
    }

    /**
     * Create an instance of {@link IdProdutoRequest }
     * 
     */
    public IdProdutoRequest createIdProdutoRequest() {
        return new IdProdutoRequest();
    }

}
